from pydantic import BaseModel, Field
from typing import List, Optional, Any

class ChatResponse(BaseModel):
    status: str = Field("success", description="Status of the request (e.g. success, error).")
    response: str = Field(..., description="The answer generated by the system.")
    sources: List[dict] = Field(default_factory=list, description="List of source document references used for the response.")

class ErrorResponse(BaseModel):
    status: str = "error"
    message: str = Field(..., description="The error message details.")

class HealthResponse(BaseModel):
    status: str = Field("ok", description="Status of the API.")
    database: str = Field(..., description="Status of ChromaDB connectivity.")
    embedding_model: str = Field(..., description="Status of the embedding generator model loading.")

class UploadResponse(BaseModel):
    status: str = Field(..., description="Upload status (e.g., success, error).")
    message: str = Field(..., description="A short summary of the processing outcome.")
    extracted_text: Optional[str] = Field(None, description="Extracted plain text for PDF files.")
    result: Optional[Any] = Field(None, description="Image processing mock service result.")
    file_path: Optional[str] = Field(None, description="Path of the processed file.")
