import chromadb
from langchain_core.documents import Document


def create_vector_store(
    documents: list[Document],
    embeddings,
    persist_directory: str = "./chroma_db",
    collection_name: str = "airline_knowledge_base",
):
    """
    Store document embeddings inside a ChromaDB collection.

    Args:
        documents: List of LangChain Document objects.
        embeddings: Embeddings generated by SentenceTransformer.
        persist_directory: Directory where ChromaDB stores data.
        collection_name: Name of the ChromaDB collection.

    Returns:
        ChromaDB collection object.
    """

    client = chromadb.PersistentClient(path=persist_directory)

    collection = client.get_or_create_collection(
        name=collection_name
    )

    ids = []
    texts = []
    metadatas = []

    for index, document in enumerate(documents):
        ids.append(f"chunk_{index}")
        texts.append(document.page_content)
        metadatas.append(document.metadata)

    collection.add(
        ids=ids,
        documents=texts,
        embeddings=embeddings.tolist(),
        metadatas=metadatas,
    )

    return collection
